import { FIELDS, fieldSlug } from "./fields.js";

/** @typedef {import("./search.js").Parallel} Parallel */
/** @typedef {import("./grouping.js").FieldGroup} FieldGroup */
/** @typedef {import("./bridge.js").BridgeResult} BridgeResult */

/**
 * The state of one card's Bridge, held in app state so a repaint (a new page of
 * Parallels, another card's Bridge arriving) never wipes it.
 *
 * The failure state carries nothing: every way a Bridge can fail — no key
 * stored, a key the API rejects, a rate limit, a network error, a reply that
 * will not parse — renders the same message, so there is nothing per-case to
 * hold (issue #15).
 *
 * A ready Bridge can be collapsed out of the way. `collapsed` is held in state
 * rather than in the DOM for the same reason the Bridge itself is: a repaint
 * rebuilds the card from scratch, and a Bridge folded away must stay folded away
 * (issue #16). It is set on arrival rather than left optional, so there is only
 * one way to say "open".
 *
 * @typedef {{ status: "pending" }
 *   | { status: "ready", result: BridgeResult, collapsed: boolean }
 *   | { status: "error" }} BridgeCardState
 */

/** The label on the control that asks for a Bridge. */
const BRIDGE_BUTTON_LABEL = "Build a Bridge";

/** Shown while the model is working. */
const BRIDGE_PENDING_LABEL = "Building a Bridge…";

/**
 * The one message shown when a Bridge cannot be generated. Deliberately the
 * same for every cause — no key stored, a key the API rejects, a rate limit, a
 * network error, a reply that will not parse — because a person can act on
 * exactly two things: their key, or trying again. The card offers both, and the
 * app never has to know whether a key exists (issue #15).
 *
 * It points at the key without claiming which cause fired: the app cannot tell
 * a missing key from a rejected one, and telling someone with a bad key to just
 * wait would send them away from the one thing they can fix. The settings page
 * is named in the text rather than linked, so the message stays a sentence and
 * not a navigation control sitting inside a card.
 */
const BRIDGE_FAILURE_MESSAGE =
  "Couldn’t generate a Bridge. Check the Anthropic API key on the settings page, then try again.";

/** The label on the control that asks for the same Bridge again. */
const BRIDGE_RETRY_LABEL = "Try again";

/**
 * The labels on the control that folds a Bridge away and brings it back. It is
 * deliberately a different control from {@link BRIDGE_BUTTON_LABEL}: the two sit
 * in the same place on the card and only one of them spends money, so they must
 * not be one button whose meaning depends on state (issue #16).
 */
const BRIDGE_HIDE_LABEL = "Hide Bridge";
const BRIDGE_SHOW_LABEL = "Show Bridge";

/**
 * The line under every Bridge marking it as generated text, not Wikipedia's —
 * this doubles as the CC BY-SA boundary marker, since the source article is
 * already linked in the same card.
 */
const BRIDGE_DISCLAIMER =
  "Generated by AI from the lead section — check it against the article before relying on it. Not Wikipedia’s text.";

/**
 * Marks a Bridge whose Strength the model judged `loose`. Only loose Bridges
 * carry a marker: a strong one is the unremarkable case and saying so would be
 * noise (ADR-0005).
 */
const LOOSE_BRIDGE_LABEL = "Loose — the shared structure is only partial.";

/**
 * Fill a `<select>` with the given Fields, keeping whatever placeholder
 * `<option value="">` it already has as the first entry. Re-runnable: any
 * previously added Field options are replaced, so the shell can render
 * {@link FIELDS} immediately and then swap in the Corpus's Fields once loaded.
 *
 * @param {HTMLSelectElement} select
 * @param {readonly string[]} [fields]
 */
export function populateHomeFieldOptions(select, fields = FIELDS) {
  for (const option of [...select.options]) {
    if (option.value !== "") option.remove();
  }
  const fragment = document.createDocumentFragment();
  for (const field of fields) {
    const option = document.createElement("option");
    option.value = field;
    option.textContent = field;
    fragment.append(option);
  }
  select.append(fragment);
}

/**
 * A Field-coloured tag, e.g. on a Parallel card.
 * @param {string} field
 * @returns {HTMLSpanElement}
 */
export function fieldTag(field) {
  const tag = document.createElement("span");
  tag.className = `field-tag field-tag--${fieldSlug(field)}`;
  tag.textContent = field;
  return tag;
}

/**
 * A `<p>` with a class and text, optionally a live region. The Bridge area
 * builds every one of its lines this way.
 * @param {string} className
 * @param {string} text
 * @param {boolean} [status]  Add `role="status"` so screen readers announce it.
 * @returns {HTMLParagraphElement}
 */
function para(className, text, status = false) {
  const p = document.createElement("p");
  p.className = className;
  p.textContent = text;
  if (status) p.setAttribute("role", "status");
  return p;
}

/**
 * A control in the Bridge area. Every one carries the Parallel's URL, which is
 * how the app's single delegated click handler knows which card was clicked.
 * The class is what says which of the two things a click means — ask for a
 * Bridge, which spends a request, or fold one away, which does not — so the two
 * never share it.
 *
 * @param {Parallel} parallel
 * @param {string} className
 * @param {string} label
 * @returns {HTMLButtonElement}
 */
function bridgeControl(parallel, className, label) {
  const button = document.createElement("button");
  button.type = "button";
  button.className = className;
  button.dataset.bridgeUrl = parallel.url;
  button.textContent = label;
  return button;
}

/**
 * The control that asks for a Bridge for `parallel`. The retry after a failure
 * is the same control under another label, so one delegated click handler in
 * the app serves both and a retry is simply the request made again.
 *
 * @param {Parallel} parallel
 * @param {string} label
 * @returns {HTMLButtonElement}
 */
function bridgeButton(parallel, label) {
  return bridgeControl(parallel, "parallel__bridge-button", label);
}

/**
 * The control that folds a rendered Bridge away, or brings it back. It sits at
 * the top of the Bridge area in both states so it does not move under the
 * pointer when clicked. It takes the card's own `collapsed` flag rather than a
 * label and a separate expanded bit, so the label and the ARIA state cannot
 * disagree.
 *
 * @param {Parallel} parallel
 * @param {boolean} collapsed
 * @returns {HTMLButtonElement}
 */
function bridgeToggle(parallel, collapsed) {
  const button = bridgeControl(
    parallel,
    "parallel__bridge-toggle",
    collapsed ? BRIDGE_SHOW_LABEL : BRIDGE_HIDE_LABEL,
  );
  button.setAttribute("aria-expanded", String(!collapsed));
  return button;
}

/**
 * The Bridge area of a card: the "ask for a Bridge" control, or — once asked —
 * the pending state, the Bridge, or the one failure message with a control to
 * ask again. A Bridge the model judged `loose` renders in full like any other,
 * with a marker above it saying so. A rendered Bridge carries a control that
 * folds it away and brings it back, which never reaches the generator. Rendered
 * purely from `state`, so a repaint restores whatever the card had — open,
 * collapsed, pending or failed.
 *
 * @param {Parallel} parallel
 * @param {BridgeCardState} [state]
 * @returns {HTMLDivElement}
 */
export function bridgeSection(parallel, state) {
  const wrap = document.createElement("div");
  wrap.className = "parallel__bridge";

  if (!state) {
    wrap.append(bridgeButton(parallel, BRIDGE_BUTTON_LABEL));
    return wrap;
  }

  if (state.status === "pending") {
    wrap.append(para("parallel__bridge-pending", BRIDGE_PENDING_LABEL, true));
    return wrap;
  }

  if (state.status === "error") {
    wrap.append(
      para("parallel__bridge-error", BRIDGE_FAILURE_MESSAGE, true),
      bridgeButton(parallel, BRIDGE_RETRY_LABEL),
    );
    return wrap;
  }

  const { result } = state;

  wrap.append(bridgeToggle(parallel, state.collapsed));
  if (state.collapsed) return wrap;

  if (result.strength === "loose") {
    wrap.append(
      para(
        "parallel__bridge-strength parallel__bridge-strength--loose",
        LOOSE_BRIDGE_LABEL,
      ),
    );
  }

  wrap.append(para("parallel__bridge-summary", result.summary));

  const list = document.createElement("ul");
  list.className = "parallel__bridge-correspondences";
  for (const pair of result.correspondences) {
    const item = document.createElement("li");
    item.textContent = `${pair.challenge} ↔ ${pair.subject}`;
    list.append(item);
  }
  wrap.append(list);

  wrap.append(para("parallel__bridge-note", BRIDGE_DISCLAIMER));
  return wrap;
}

/**
 * One Parallel: linked title, Field tag, Closeness, Lead Section, and the Bridge
 * area.
 * @param {Parallel} parallel
 * @param {BridgeCardState} [bridgeState]
 * @returns {HTMLLIElement}
 */
export function parallelCard(parallel, bridgeState) {
  const item = document.createElement("li");
  item.className = "parallel";

  const heading = document.createElement("h4");
  heading.className = "parallel__title";
  const link = document.createElement("a");
  link.href = parallel.url;
  link.textContent = parallel.title;
  link.rel = "noopener";
  link.target = "_blank";
  heading.append(link);

  const meta = document.createElement("p");
  meta.className = "parallel__meta";
  meta.append(fieldTag(parallel.field));
  const closeness = document.createElement("span");
  closeness.className = "parallel__closeness";
  closeness.textContent = `Closeness ${parallel.closeness}`;
  meta.append(closeness);

  const lead = document.createElement("p");
  lead.className = "parallel__lead";
  lead.textContent = parallel.leadSection;

  item.append(heading, meta, lead, bridgeSection(parallel, bridgeState));
  return item;
}

/**
 * Replace the contents of `container` with the grouped Parallels. An empty
 * `groups` list renders a short "nothing found" note.
 *
 * `bridgeFor` maps a Parallel to its {@link BridgeCardState}, or `undefined`
 * when no Bridge has been asked for. It is passed in rather than read from a
 * module global so `renderGroups` stays a pure function of its arguments: every
 * repaint rebuilds each card's Bridge from state, so a "Show 6 more" repaint
 * never wipes an open Bridge.
 *
 * @param {HTMLElement} container
 * @param {FieldGroup[]} groups
 * @param {(parallel: Parallel) => BridgeCardState | undefined} [bridgeFor]
 */
export function renderGroups(container, groups, bridgeFor = () => undefined) {
  container.replaceChildren();

  if (groups.length === 0) {
    const note = document.createElement("p");
    note.className = "parallels-empty";
    note.textContent = "No Parallels for that Challenge. Try rephrasing it.";
    container.append(note);
    return;
  }

  for (const group of groups) {
    const section = document.createElement("section");
    section.className = "field-group";

    const heading = document.createElement("h3");
    heading.className = `field-group__heading field-group__heading--${fieldSlug(group.field)}`;
    heading.textContent = group.field;

    const list = document.createElement("ul");
    list.className = "parallel-list";
    for (const parallel of group.parallels) {
      list.append(parallelCard(parallel, bridgeFor(parallel)));
    }

    section.append(heading, list);
    container.append(section);
  }
}
