import { FIELDS, fieldSlug } from "./fields.js";

/** @typedef {import("./search.js").Parallel} Parallel */
/** @typedef {import("./grouping.js").FieldGroup} FieldGroup */
/** @typedef {import("./bridge.js").BridgeResult} BridgeResult */

/**
 * The state of one card's Bridge, held in app state so a repaint (a new page of
 * Parallels, another card's Bridge arriving) never wipes it.
 *
 * @typedef {{ status: "pending" }
 *   | { status: "ready", result: BridgeResult }
 *   | { status: "error", message: string }} BridgeCardState
 */

/** The label on the control that asks for a Bridge. */
const BRIDGE_BUTTON_LABEL = "Build a Bridge";

/** Shown while the model is working. */
const BRIDGE_PENDING_LABEL = "Building a Bridge…";

/**
 * The line under every Bridge marking it as generated text, not Wikipedia's —
 * this doubles as the CC BY-SA boundary marker, since the source article is
 * already linked in the same card.
 */
const BRIDGE_DISCLAIMER =
  "Generated by AI from the lead section — check it against the article before relying on it. Not Wikipedia’s text.";

/**
 * Marks a Bridge whose Strength the model judged `loose`. Only loose Bridges
 * carry a marker: a strong one is the unremarkable case and saying so would be
 * noise (ADR-0005).
 */
const LOOSE_BRIDGE_LABEL = "Loose — the shared structure is only partial.";

/**
 * Fill a `<select>` with the given Fields, keeping whatever placeholder
 * `<option value="">` it already has as the first entry. Re-runnable: any
 * previously added Field options are replaced, so the shell can render
 * {@link FIELDS} immediately and then swap in the Corpus's Fields once loaded.
 *
 * @param {HTMLSelectElement} select
 * @param {readonly string[]} [fields]
 */
export function populateHomeFieldOptions(select, fields = FIELDS) {
  for (const option of [...select.options]) {
    if (option.value !== "") option.remove();
  }
  const fragment = document.createDocumentFragment();
  for (const field of fields) {
    const option = document.createElement("option");
    option.value = field;
    option.textContent = field;
    fragment.append(option);
  }
  select.append(fragment);
}

/**
 * A Field-coloured tag, e.g. on a Parallel card.
 * @param {string} field
 * @returns {HTMLSpanElement}
 */
export function fieldTag(field) {
  const tag = document.createElement("span");
  tag.className = `field-tag field-tag--${fieldSlug(field)}`;
  tag.textContent = field;
  return tag;
}

/**
 * A `<p>` with a class and text, optionally a live region. The Bridge area
 * builds every one of its lines this way.
 * @param {string} className
 * @param {string} text
 * @param {boolean} [status]  Add `role="status"` so screen readers announce it.
 * @returns {HTMLParagraphElement}
 */
function para(className, text, status = false) {
  const p = document.createElement("p");
  p.className = className;
  p.textContent = text;
  if (status) p.setAttribute("role", "status");
  return p;
}

/**
 * The Bridge area of a card: the "ask for a Bridge" control, or — once asked —
 * the pending state, the Bridge, or a one-line failure. A Bridge the model
 * judged `loose` renders in full like any other, with a marker above it saying
 * so. Rendered purely from `state`, so a repaint restores whatever the card had.
 *
 * @param {Parallel} parallel
 * @param {BridgeCardState} [state]
 * @returns {HTMLDivElement}
 */
export function bridgeSection(parallel, state) {
  const wrap = document.createElement("div");
  wrap.className = "parallel__bridge";

  if (!state) {
    const button = document.createElement("button");
    button.type = "button";
    button.className = "parallel__bridge-button";
    button.dataset.bridgeUrl = parallel.url;
    button.textContent = BRIDGE_BUTTON_LABEL;
    wrap.append(button);
    return wrap;
  }

  if (state.status === "pending") {
    wrap.append(para("parallel__bridge-pending", BRIDGE_PENDING_LABEL, true));
    return wrap;
  }

  if (state.status === "error") {
    wrap.append(para("parallel__bridge-pending", state.message, true));
    return wrap;
  }

  const { result } = state;

  if (result.strength === "loose") {
    wrap.append(
      para(
        "parallel__bridge-strength parallel__bridge-strength--loose",
        LOOSE_BRIDGE_LABEL,
      ),
    );
  }

  wrap.append(para("parallel__bridge-summary", result.summary));

  const list = document.createElement("ul");
  list.className = "parallel__bridge-correspondences";
  for (const pair of result.correspondences) {
    const item = document.createElement("li");
    item.textContent = `${pair.challenge} ↔ ${pair.subject}`;
    list.append(item);
  }
  wrap.append(list);

  wrap.append(para("parallel__bridge-note", BRIDGE_DISCLAIMER));
  return wrap;
}

/**
 * One Parallel: linked title, Field tag, Closeness, Lead Section, and the Bridge
 * area.
 * @param {Parallel} parallel
 * @param {BridgeCardState} [bridgeState]
 * @returns {HTMLLIElement}
 */
export function parallelCard(parallel, bridgeState) {
  const item = document.createElement("li");
  item.className = "parallel";

  const heading = document.createElement("h4");
  heading.className = "parallel__title";
  const link = document.createElement("a");
  link.href = parallel.url;
  link.textContent = parallel.title;
  link.rel = "noopener";
  link.target = "_blank";
  heading.append(link);

  const meta = document.createElement("p");
  meta.className = "parallel__meta";
  meta.append(fieldTag(parallel.field));
  const closeness = document.createElement("span");
  closeness.className = "parallel__closeness";
  closeness.textContent = `Closeness ${parallel.closeness}`;
  meta.append(closeness);

  const lead = document.createElement("p");
  lead.className = "parallel__lead";
  lead.textContent = parallel.leadSection;

  item.append(heading, meta, lead, bridgeSection(parallel, bridgeState));
  return item;
}

/**
 * Replace the contents of `container` with the grouped Parallels. An empty
 * `groups` list renders a short "nothing found" note.
 *
 * `bridgeFor` maps a Parallel to its {@link BridgeCardState}, or `undefined`
 * when no Bridge has been asked for. It is passed in rather than read from a
 * module global so `renderGroups` stays a pure function of its arguments: every
 * repaint rebuilds each card's Bridge from state, so a "Show 6 more" repaint
 * never wipes an open Bridge.
 *
 * @param {HTMLElement} container
 * @param {FieldGroup[]} groups
 * @param {(parallel: Parallel) => BridgeCardState | undefined} [bridgeFor]
 */
export function renderGroups(container, groups, bridgeFor = () => undefined) {
  container.replaceChildren();

  if (groups.length === 0) {
    const note = document.createElement("p");
    note.className = "parallels-empty";
    note.textContent = "No Parallels for that Challenge. Try rephrasing it.";
    container.append(note);
    return;
  }

  for (const group of groups) {
    const section = document.createElement("section");
    section.className = "field-group";

    const heading = document.createElement("h3");
    heading.className = `field-group__heading field-group__heading--${fieldSlug(group.field)}`;
    heading.textContent = group.field;

    const list = document.createElement("ul");
    list.className = "parallel-list";
    for (const parallel of group.parallels) {
      list.append(parallelCard(parallel, bridgeFor(parallel)));
    }

    section.append(heading, list);
    container.append(section);
  }
}
